import { FormEvent, useState } from 'react'
import { Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { Activity, Bell, BookOpen, Building2, CalendarDays, ClipboardCheck, FileText, HeartHandshake, LockKeyhole, LogOut, MessageCircle, ShieldCheck, Stethoscope, UserRound, Users } from 'lucide-react'
import { supabase } from './supabase'
import { useAuth } from './auth'
import type { Portal } from './types'

const portalCopy: Record<Portal, { title: string; subtitle: string; icon: typeof Users }> = {
  parent: { title: 'Parent Portal', subtitle: 'Stay connected to your child’s learning, care and support.', icon: HeartHandshake },
  staff: { title: 'Staff Portal', subtitle: 'For teachers, special educators and therapists.', icon: Stethoscope },
  admin: { title: 'Institute Admin', subtitle: 'Secure institute access for authorized administrators.', icon: ShieldCheck },
}

function Shell({ children }: { children: React.ReactNode }) {
  return <main className="app-shell"><div className="ambient ambient-one"/><div className="ambient ambient-two"/>{children}</main>
}
function Brand(){return <div className="brand"><div className="brand-mark">A</div><div><div className="brand-name">ANTAR</div><div className="brand-tagline">Every child leaves a mark.</div></div></div>}

function Landing(){const navigate=useNavigate();return <Shell><section className="auth-layout"><div className="intro-panel"><Brand/><div className="intro-copy"><span className="eyebrow">Secure care communication</span><h1>One calm place for families, care teams and institutions.</h1><p>ANTAR brings learning, care updates and communication together in one private institution-connected space.</p><div className="trust-row"><span><LockKeyhole size={17}/> Private by design</span><span><Building2 size={17}/> Institution connected</span></div></div></div><div className="portal-panel"><div className="portal-card"><div className="panel-heading"><span className="eyebrow">Choose your portal</span><h2>Welcome to ANTAR</h2><p>Select the account type assigned by your institution.</p></div><div className="portal-grid">{(Object.keys(portalCopy) as Portal[]).map(portal=>{const item=portalCopy[portal];const Icon=item.icon;return <button className="portal-option" key={portal} onClick={()=>navigate(`/login/${portal}`)}><span className="portal-icon"><Icon size={22}/></span><span><strong>{item.title}</strong><small>{item.subtitle}</small></span><span className="arrow">→</span></button>})}</div><p className="legal-copy">Access is limited to accounts authorized by a participating institution.</p></div></div></section></Shell>}

function Login(){const {portal='parent'}=useParams();const portalName=(['parent','staff','admin'].includes(portal)?portal:'parent') as Portal;const copy=portalCopy[portalName];const Icon=copy.icon;const {signIn,user,membership}=useAuth();const navigate=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);if(user&&membership)return <Navigate to="/app" replace/>;async function onSubmit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await signIn(email.trim(),password,portalName);navigate('/app',{replace:true})}catch(err){setError(err instanceof Error?err.message:'Unable to sign in.')}finally{setBusy(false)}}return <Shell><section className="single-card-wrap"><div className="login-card"><button className="back-link" onClick={()=>navigate('/')}>← All portals</button><Brand/><div className="login-title-row"><span className="portal-icon large"><Icon size={24}/></span><div><span className="eyebrow">{copy.title}</span><h1>Sign in to ANTAR</h1></div></div><p className="login-subtitle">{copy.subtitle}</p><form onSubmit={onSubmit} className="login-form"><label>Email address<input autoComplete="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><label>Password<input autoComplete="current-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" required/></label><div className="form-row"><button className="text-button" type="button" onClick={async()=>{if(!email.trim()){setError('Enter your email address first.');return}const {error:resetError}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}${import.meta.env.BASE_URL}reset-password`});setError(resetError?resetError.message:'Password reset email sent.')}}>Forgot password?</button></div>{error&&<div className="status-message">{error}</div>}<button className="primary-button" disabled={busy} type="submit">{busy?'Signing in…':'Sign in securely'}</button></form></div></section></Shell>}

function ResetPassword(){const [password,setPassword]=useState('');const [status,setStatus]=useState('');const navigate=useNavigate();return <Shell><section className="single-card-wrap"><div className="login-card"><Brand/><span className="eyebrow">Account recovery</span><h1>Choose a new password</h1><form className="login-form" onSubmit={async e=>{e.preventDefault();const {error}=await supabase.auth.updateUser({password});if(error)setStatus(error.message);else{setStatus('Password updated. You can sign in now.');setTimeout(()=>navigate('/'),1000)}}}><label>New password<input minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{status&&<div className="status-message">{status}</div>}<button className="primary-button" type="submit">Update password</button></form></div></section></Shell>}

type Tile={title:string;desc:string;icon:typeof Users}
const parentTiles:Tile[]=[{title:'My Child',desc:'Profile and support overview',icon:UserRound},{title:'Daily School Report',desc:'See today’s learning and care update',icon:BookOpen},{title:'Attendance',desc:'Review attendance records',icon:ClipboardCheck},{title:'Schedule',desc:'Classes, therapy and activities',icon:CalendarDays},{title:'Health & Therapy',desc:'Care and therapy information',icon:Activity},{title:'Documents',desc:'Secure reports and records',icon:FileText},{title:'Messages',desc:'Talk with the care team',icon:MessageCircle},{title:'Appointments',desc:'Upcoming meetings and sessions',icon:Stethoscope},{title:'Timeline & Notifications',desc:'Important updates in one place',icon:Bell}]
const staffTiles:Tile[]=[{title:'Assigned Children',desc:'Children currently in your care',icon:Users},{title:'Daily Reports',desc:'Create and review daily updates',icon:BookOpen},{title:'Attendance',desc:'Record and review attendance',icon:ClipboardCheck},{title:'Schedule',desc:'Your sessions and activities',icon:CalendarDays},{title:'Messages',desc:'Communicate securely with families',icon:MessageCircle},{title:'Care & Therapy',desc:'Record permitted care updates',icon:Activity}]
const adminTiles:Tile[]=[{title:'Students',desc:'Institution student overview',icon:Users},{title:'Staff',desc:'Teachers, educators and therapists',icon:Stethoscope},{title:'Assignments',desc:'Manage staff-child coordination',icon:HeartHandshake},{title:'Attendance & Reports',desc:'Institution-wide oversight',icon:ClipboardCheck},{title:'Messaging',desc:'Communication and announcements',icon:MessageCircle},{title:'Care Coordination',desc:'Appointments and care operations',icon:Activity}]
function RoleDashboard({title,subtitle,tiles}:{title:string;subtitle:string;tiles:Tile[]}){return <><div className="dashboard-hero"><span className="eyebrow">{title}</span><h1>{subtitle}</h1><p>Your authenticated ANTAR workspace. Core modules are now separated by verified institution role.</p></div><div className="feature-grid">{tiles.map(({title,desc,icon:Icon})=><button className="feature-card" key={title} type="button"><span className="feature-icon"><Icon size={21}/></span><span><strong>{title}</strong><small>{desc}</small></span><span className="arrow">→</span></button>)}</div></>}

function ProtectedApp(){const {user,membership,loading,signOut}=useAuth();const location=useLocation();if(loading)return <Shell><div className="loading-screen">Loading ANTAR…</div></Shell>;if(!user||!membership)return <Navigate to="/" replace state={{from:location}}/>;const institutionName=membership.institutions?.name??'Your institution';const role=membership.role;const roleLabel=role.replaceAll('_',' ');let content;if(role==='parent')content=<RoleDashboard title="Parent Portal" subtitle="Your child’s day, care and progress — together." tiles={parentTiles}/>;else if(role==='institute_admin')content=<RoleDashboard title="Institute Admin" subtitle="A clear view of your institution." tiles={adminTiles}/>;else content=<RoleDashboard title="Staff Portal" subtitle="Support every child with a connected care workspace." tiles={staffTiles}/>;return <Shell><section className="dashboard-shell"><header className="dashboard-header"><Brand/><div className="header-actions"><div className="account-chip"><small>{institutionName}</small><strong>{roleLabel}</strong></div><button className="secondary-button" onClick={()=>void signOut()}><LogOut size={17}/> Logout</button></div></header><div className="dashboard-content">{content}<div className="identity-strip"><ShieldCheck size={18}/><span>Protected session</span><span>{user.email??'Authenticated user'}</span><span>{institutionName}</span></div></div></section></Shell>}

export default function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/login/:portal" element={<Login/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/app" element={<ProtectedApp/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
